project_id = "djdunqekorilwsfjmzan"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.parse-shift-voice]
enabled = true

[functions.transcribe-audio]
enabled = true

[functions.delete-account]
enabled = true
